# These are variables expected to be set to run HC

devise_secret_key: "secret"
aws_bucket: "blah"
aws_access_key_id: "secret"
aws_secret_access_key: "secret"
sendgrid_username: "blah"
sendgrid_password: "blah"
domain: "blah"
email: "test@example.com"
production_ip: "127.0.0.1"
secret_key_base: "12345"
papertrail_port: "12345"
