# These are variables expected to be set to run HC

aws_bucket: "bucket"
aws_access_key_id: "secret"
aws_secret_access_key: "secret"
bugsnag: "12345"
codeclimate_repo_token: "12345"
domain: "http://example.com"
email: "test@example.com"
production_ip: "127.0.0.1"
sendgrid_username: "blah"
sendgrid_password: "blah"
